### ISSUE TITLE
Arm6 support for raspberry Pi zero?

### ISSUE THREAD

**Issue by jorjun** [sirredbeard/nim_lang_snap#12]
Currently compiling nim-lang from source... think it is going to take all day... if I can help please let me know how..

**Comment by sirredbeard** [comment]
This is the repository for the snap package of nim-lang. For general nim-lang questions, like building nim-lang from source, please see the [Nim forum](https://forum.nim-lang.org/). Building on the Pi 0 will take some time.

**Comment by jorjun** [comment]
Please could provide an arm6 snap binary to go along with the other architectures?

**Comment by sirredbeard** [comment]
I have added armhf and arm64 builds of the Nim snap.

**Comment by jorjun** [comment]
Brilliant news. Thanks so much for doing this.
