### ISSUE TITLE
Nim unable to access gcc or gcc libraries

### ISSUE THREAD

**Issue by pixelr0** [sirredbeard/nim_lang_snap#2]
i have the hello.nim file in my home folder
when trying to compile/run i get this error

```
~$ nim c -r hello.nim 
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: hello [Processing]
Error: cannot open '/home/pixel/hello.nim'
```

i'm using nim-lang 1.0 front the stable channel (on Ubuntu 16.04)
channels:
  stable:    1.0.0 2019-09-25 (15) 7MB -

**Comment by pixelr0** [comment]
um.. if i move the hello.nim to :~/snap/nim-lang/ then i get a diff error
```
~/snap/nim-lang$ nim c -r hello.nim 
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: hello [Processing]
CC: stdlib_io.nim
CC: stdlib_system.nim
CC: hello.nim
Error: execution of an external compiler program 'gcc -c   -I/snap/nim-lang/15/lib -I/home/pixel/snap/nim-lang -o /home/pixel/snap/nim-lang/15/.cache/nim/hello_d/stdlib_io.nim.c.o /home/pixel/snap/nim-lang/15/.cache/nim/hello_d/stdlib_io.nim.c' failed with exit code: 127

/bin/sh: 1: gcc: not found
```

i do have gcc installed.

so it looks to me that there are 2 errors? one with maybe permission to access home and second something with gcc path? o_O

**Comment by sirredbeard** [comment]
So I think for the first issue I need to define a home interface in the snap and add documentation about manually enabling it.

For the second issue I think I need to bundle gcc in the snap itself.

I am working on both of these now.

**Comment by sirredbeard** [comment]
I have fixes pending but something is causing GitHub Actions to hang, and I cannot cancel builds ([not alone](https://github.community/t5/GitHub-Actions/Can-t-cancel-hung-job-quot-Failed-to-cancel-check-suite-quot/td-p/32673) apparently), so I am stuck waiting 6 hours for my existing builds to time out.

**Comment by pixelr0** [comment]
great! thanks :P

**Comment by pixelr0** [comment]
i already see the progress in the new build 
```
~$ snap connections nim-lang
Interface  Plug              Slot      Notes
home       nim-lang:home     :home     -
network    nim-lang:network  :network  -
```

and indeed the first bug is closed 

```
:~$ nim c -r hello.nim 
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: hello [Processing]
CC: stdlib_io.nim
CC: stdlib_system.nim
CC: hello.nim
Error: execution of an external compiler program 'gcc -c   -I/snap/nim-lang/23/lib -I/home/pixel -o /home/pixel/snap/nim-lang/23/.cache/nim/hello_d/stdlib_io.nim.c.o /home/pixel/snap/nim-lang/23/.cache/nim/hello_d/stdlib_io.nim.c' failed with exit code: 1

gcc: error trying to exec 'cc1': execvp: No such file or directory
```

**Comment by sirredbeard** [comment]
Home and network are working.

I have been working through a few different approaches with gcc, clang, and related libraries.

I was copying them, which caused symbolic link problems, now I am trying the layout approach in the Snap YAML.

**Comment by sirredbeard** [comment]
I am getting
```
gcc: error trying to exec 'cc1': execvp: No such file or directory
```
cc1 looks like it's there: 
```
$ sudo find / -name "cc1"
/snap/rust/17/usr/lib/gcc/x86_64-linux-gnu/7/cc1
/snap/nim-lang/24/usr/lib/gcc/x86_64-linux-gnu/5/cc1
/snap/nim-lang/24/usr/lib/gcc/x86_64-linux-gnu/5.4.0/cc1
/snap/nim-lang-nightly/22/usr/lib/gcc/x86_64-linux-gnu/5/cc1
/snap/nim-lang-nightly/22/usr/lib/gcc/x86_64-linux-gnu/5.4.0/cc1
```
But there's nothing actually in that folder:
```
$ ls lib
ubuntu@ubuntu:/snap/nim-lang-nightly/current/usr$  
```

**Comment by sirredbeard** [comment]
So I am now very sure I am way over-thinking this problem and have a much simpler solution in mind.

I don't think I need layout, I need to be using stage-packages instead of this copying nonsense,. I didn't need to do all that. 😪

**Comment by pixelr0** [comment]
:D don't stress yourself too much, you can ask for help here https://forum.snapcraft.io/c/snapcraft 
there are many Canonical people that can help

**Comment by sirredbeard** [comment]
I jumped on to #snapcraft and asked a couple questions there.

The problem I am running into now:

```
root@vultr:~# nim-lang.nim c -r hello.nim
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: hello [Processing]
CC: stdlib_io.nim
CC: stdlib_system.nim
Error: execution of an external compiler program 'gcc -c   -I/snap/nim-lang/31/lib -I/root -o /root/snap/nim-lang/31/.cache/nim/hello_d/stdlib_io.nim.c.o /root/snap/nim-lang/31/.cache/nim/hello_d/stdlib_io.nim.c' failed with exit code: 1

In file included from /snap/nim-lang/31/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/syslimits.h:7:0,
                 from /snap/nim-lang/31/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/limits.h:34,
                 from /snap/nim-lang/31/lib/nimbase.h:257,
                 from /root/snap/nim-lang/31/.cache/nim/hello_d/stdlib_io.nim.c:9:
/snap/nim-lang/31/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
compilation terminated.
```

Which is frustrating because I can see /snap/nim-lang/31/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed/limits.h there. 

![Annotation 2019-09-26 160734](https://user-images.githubusercontent.com/33820650/65727622-43d85000-e086-11e9-925c-2f769528a2ce.png)

Maybe it's calling another limits.?

**Comment by sirredbeard** [comment]
I am preparing a detailed bug report upstream to get some guidance on this issue.

**Comment by sirredbeard** [comment]
Report is [here](https://forum.snapcraft.io/t/difficulty-accessing-libc6-dev-headers-from-nim-language-snap/13487).

**Comment by sirredbeard** [comment]
Fixed by reverting to classic confinement.
